"""add task due date and priority

Revision ID: 9502da5918d3
Revises:
Create Date: 2026-08-29 12:12:36.400080

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9502da5918d3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("due_at", sa.DateTime(), nullable=True))
    op.add_column(
        "tasks",
        sa.Column(
            "priority",
            sa.String(length=10),
            nullable=False,
            server_default="normal",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "priority")
    op.drop_column("tasks", "due_at")
    # ### end Alembic commands ###
