"""add reminder sent status

Revision ID: ad429973511a
Revises: d22382232f73
Create Date: 2026-09-27 21:26:50.174767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad429973511a"
down_revision: Union[str, Sequence[str], None] = "d22382232f73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminders",
        sa.Column(
            "sent",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reminders", "sent")
    # ### end Alembic commands ###
